function [fitresult, gof] = createFit(js, ls)
%CREATEFIT(JS,LS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : js
%      Y Output: ls
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Aug-2022 12:58:07


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( js, ls );

% Set up fittype and options.
ft = fittype( 'poly9' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'ls vs. js', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'js', 'Interpreter', 'none' );
ylabel( 'ls', 'Interpreter', 'none' );
grid on


