function [fitresult, gof] = createFit(js, ls)
%CREATEFIT(JS,LS)
%  Create a fit.
%
%  Data for 'CurveFit' fit:
%      X Input : js
%      Y Output: ls
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Aug-2022 19:32:26


%% Fit: 'CurveFit'.
[xData, yData] = prepareCurveData( js, ls );

% Set up fittype and options.
ft = fittype( 'A*sin(x+phi)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.792207329559554 0.959492426392903];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'CurveFit' );
h = plot( fitresult, xData, yData );
legend( h, 'ls vs. js', 'CurveFit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'js', 'Interpreter', 'none' );
ylabel( 'ls', 'Interpreter', 'none' );
grid on


